### ISSUE TITLE
Week1

### ISSUE THREAD

**Issue by SaschaVanEssen** [dboekhout/CSRIB#1]
Je hebt nog geen processbook. Zorg dat je elke dag je voortgang naar GitHub pusht en je PROCESS.md update. De structuur van je GitHub en je DESIGN.md ziet er goed uit!

**Comment by dboekhout** [comment]
Process Book has been added, you can find it here: [Process Book](https://github.com/dboekhout/CSRIB/blob/master/PROCESS.md)

**Comment by dboekhout** [comment]
Closing issue.
