### ISSUE TITLE
Week2

### ISSUE THREAD

**Issue by SaschaVanEssen** [dboekhout/CSRIB#2]
In je PROCESS.md hoeven geen plaatjes van hoe ver je bent met je site. Het is heel leuk dat het gifjes zijn, maar de focus in je process book moet liggen op de belangrijke beslissingen die je genomen hebt en waar je tegenaan bent gelopen, niet op hoe ver je nu bent (sommige dagen doe je dat wel, andere niet)

**Comment by dboekhout** [comment]
Format van process book vanaf week 3 aangepast. Bevat op dit moment minder progressie en meer beslissingen die zijn gemaakt. Plaatjes van de website worden niet meer toegevoegd.
